services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "express"
  server:
    build: .
    ports:
      - "5588:5588"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/express?schema=public"
    depends_on:
      - db
    command: sh -c "sleep 5;bun prisma migrate dev --name=init;bun run src/index.ts"
