
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "express"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  server:
    build: .
    ports:
      - "5588:5588"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/express?schema=public"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
      bun prisma migrate dev --name=init && 
      bun run ."
volumes:
  db_data:

